// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions]
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL2PFleUTaCQtrTMHpnoJQH59WYcyZ9CY',
    appId: '1:845305339516:web:cdadbc00a49e7ccfb2b3f9',
    messagingSenderId: '845305339516',
    projectId: 'ifound-mobileapp-52771',
    authDomain: 'ifound-mobileapp-52771.firebaseapp.com',
    storageBucket: 'ifound-mobileapp-52771.firebasestorage.app',
    measurementId: 'G-LQS436LVMS',
  );
  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlRWQ81YujhTLpVPXxy034HQjnL4JU3sM',
    appId: '1:845305339516:android:88c83073a58c5debb2b3f9',
    messagingSenderId: '845305339516',
    projectId: 'ifound-mobileapp-52771',
    storageBucket: 'ifound-mobileapp-52771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDImwGH3QUfDDnwCy5F-qhexmfN3m2OZu0',
    appId: '1:845305339516:ios:9943040263983a40b2b3f9',
    messagingSenderId: '845305339516',
    projectId: 'ifound-mobileapp-52771',
    storageBucket: 'ifound-mobileapp-52771.firebasestorage.app',
    iosClientId: '845305339516-6f1176mngj775ge4vu489qiuj1rsqi5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDImwGH3QUfDDnwCy5F-qhexmfN3m2OZu0',
    appId: '1:845305339516:ios:9943040263983a40b2b3f9',
    messagingSenderId: '845305339516',
    projectId: 'ifound-mobileapp-52771',
    storageBucket: 'ifound-mobileapp-52771.firebasestorage.app',
    iosClientId: '845305339516-6f1176mngj775ge4vu489qiuj1rsqi5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL2PFleUTaCQtrTMHpnoJQH59WYcyZ9CY',
    appId: '1:845305339516:web:705fd0b924c79119b2b3f9',
    messagingSenderId: '845305339516',
    projectId: 'ifound-mobileapp-52771',
    authDomain: 'ifound-mobileapp-52771.firebaseapp.com',
    storageBucket: 'ifound-mobileapp-52771.firebasestorage.app',
    measurementId: 'G-C0QBM2KWDN',
  );

}